[project]
name = "remote-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.119.1",
    "fastmcp>=2.12.5",
    "pydantic>=2.12.3",
    "uvicorn>=0.38.0",
]
